services:
  web:
    build:
      context: ./python
    ports:
      - "5000:5000"

  db:
    image: mysql:8.4.0
    environment:
      - MYSQL_DATABASE=hello
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=password01
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ./mysql/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/2.sql