services:
  web:
    image: demo4-web:1.0
    ports:
      - "5000:5000"
    healthcheck:
      test: "curl -f localhost:5000"
      interval: 5s
      timeout: 5s
      retries: 10

  db:
    image: demo4-db:1.0
    environment:
      - MYSQL_DATABASE=hello
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=${XX_PASSWORD:-password01}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser01", "-ppassword01"]
      interval: 5s
      timeout: 5s
      retries: 10