services:
  mysql:
    image: mysql:8.4.0
    environment:
      - MYSQL_DATABASE=hello
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=password01
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - xyz:/var/lib/mysql
volumes:
  xyz: