services:
  php-apache:
    container_name: php01
    image: php:8.3.6-apache-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: db
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: 'MYSQL_ROOT_PASSWORD'
      MYSQL_DATABASE: 'hello'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"